namespace: monk-mysql-master-slave

stack:
  defines: process-group
  runnable-list:
    - monk-mysql-master-slave/master
    - monk-mysql-master-slave/slave1
    - monk-mysql-master-slave/slave2
    - monk-mysql-master-slave/configure
  variables:
    mysql_database_repl_user: "repl"
    mysql_database_repl_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_monitor_user: "monitor"
    mysql_database_monitor_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "monk"
    mysql_master_database_port: 3306
    mysql_slave1_database_port: 3307
    mysql_slave2_database_port: 3308
    mysql_database_password: "RhgDPXPEnAgxxXYZ"
    mysql_image_tag: 5.6.47
    mysql_database_data_volume_path: /mnt/mysql
    mysql_database_data_volume_size: 60