namespace:  monk-mysql
stack:
  defines: process-group
  runnable-list:
    -  monk-mysql/db
  variables:
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "wpdb"
    mysql_database_password: 
      type: string
      value: "RhgDPXPEnAgxxXYZ"
    server_name: wordpress.burakhan.com
    mysql-image-tag: 5.6.47