namespace:  monk-mysql
stack:
  defines: process-group
  runnable-list:
    -  monk-mysql/db
  variables:
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "monk"
    mysql_database_port: 3306
    mysql_database_password: "RhgDPXPEnAgxxXYZ"
    mysql_image_tag: 5.6.47
    mysql_database_data_volume_path: /mnt/mysql
    mysql_database_data_volume_size: 60
    